name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use the version your project requires
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t "${{ secrets.DOCKER_HUB_USERNAME }}"/financialdashboard .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push financialdashboard

      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "serviceId": "srv-cs77d7q3esus73chj1d0",  
            "branch": "main"
          }' \
          https://dashboard.render.com/web/srv-cs77d7q3esus73chj1d0/deploys
